### PR TITLE
Fix check in vmi-win-guid

### LINKED ISSUE #838: vmi-win-guid not working for Windows 7 (32 bit)
I have a problem with getting a kernel GUID using `vmi-win-guid` on Windows 7 x86. The exact line that is too rigorous is:

https://github.com/libvmi/libvmi/blob/df82b484d4b7a9562dfcf66fe8ea58500e65cbf1/examples/win-guid.c#L88

... after commenting it out it prints out the GUID properly.

Variable values:
```
base_p = 0x2843000
export_header_offset = 0x344000
```

seems like the export header is mapped much further than it was expected.

Windows 7 x86 ISO file of my target:
```
4129a34d796cd49e852f68805976f8cf85325f7a4d1dd656354bbdad3ae3ee27
SW_DVD5_SA_Win_Ent_7_32BIT_English_Full_MLF_X15-70745.ISO
```

I have no clue about the suggested fix. Maybe just remove this check?

### PR DESCRIPTION
**Pull request by icedevml**
Resolve #838

### CODE REVIEW

File: examples/win-guid.c [hunk 1]
```diff
@@ -83,9 +97,8 @@ status_t is_WINDOWS_KERNEL(vmi_instance_t vmi, addr_t base_p, uint8_t *pe)
     peparse_assign_headers(pe, NULL, NULL, &optional_header_type, &optional_pe_header, NULL, NULL);
     addr_t export_header_offset = peparse_get_idd_rva(IMAGE_DIRECTORY_ENTRY_EXPORT, &optional_header_type, optional_pe_header, NULL, NULL);
 
-    // The kernel's export table is continuously allocated on the PA level with the PE header
-    // This trick may not work for other PE headers (though may work for some drivers)
-    if ( base_p + export_header_offset < base_p + VMI_PS_4KB ) {
+    // Check if kernel's export table is within the PE image boundary
+    if ( base_p + export_header_offset < base_p + get_image_size(optional_header_type, optional_pe_header) ) {
```
Comment (tklengyel) [inline examples/win-guid.c]: I would also add the export header size here.

Comment (icedevml) [reply examples/win-guid.c]: I've added a bound check for `et.name`:
```
et.name >= export_header_offset && et.name <= export_header_offset + export_header_size
```

**Comment by tklengyel** [comment]
@drakvuf-jenkins This is OK to test
